### ISSUE TITLE
fix: disable sentry when not in prod

### ISSUE THREAD

**Issue by rap2hpoutre** [SocialGouv/mano#356]
See: https://github.com/SocialGouv/mano/commit/8ce916c4fcc6e566114549f0191fe2bc2c4095cd

**Comment by arnaudambro** [comment]
Dashboard OK too : https://github.com/SocialGouv/mano/blob/2d76618192727452ee95bb5c5a8fd60e62c03d28/dashboard/src/services/sentry.js#L5

**Comment by arnaudambro** [comment]
App too

**Comment by arnaudambro** [comment]
Can we close ?
