### ISSUE TITLE
help: Make first database migration on dev mode 

### ISSUE THREAD

**Issue by lobamosa** [SocialGouv/mano#414]
Hello, 
I'm facing an issue when I get my hand on the API. It's probably nothing, but when I start the project in dev mode, I can't make the database migration correctly. Sequelize crash on shema "mano" who  does not exist, or after i have manually created it,  associations with this schema does not exist either 
I have tried to run the script initDb, and use the sequelize CLI to make migrations. 

Do you have any clue how I can make it works ? 

Thanks In  advance

**Comment by lobamosa** [comment]
step to reproduce : 
I've set up a little branch with a compose file to reproduce easily. 
https://github.com/lobamosa/mano/tree/compose-file

**Comment by rap2hpoutre** [comment]
Hello @lobamosa thank you for your message.

> Sequelize crash on shema "mano" who does not exist

You need:
 - a PostgreSQL database with `mano` schema
 - a `.env` file in`api` folder: 
```
PORT=
PGUSER=
PGHOST=
PGPASSWORD=
PGDATABASE=mydatabasename
PGPORT=
```
- A db initialized that _looks like_ this: https://github.com/SocialGouv/mano/blob/7220b6eee568c9bf6602ffcff544c103c7cc7540/tests/src/scripts/db.sql

Then you can start the API with `yarn dev` and it _should_ work. Now a word about the state of this product 😅 

Although open-source, the mano app is unfortunately not yet ready to onboard contributors: as you may have notice there is no easy way to start the project locally (sorry about that !), everything is still based on oral exchanges between actors. Helping contributors is a bit early for us, we're not ready. In other words, you are free to use it but as stated in the licence `Licensor provides the Work (and each Contributor provides its Contributions) on an "AS IS" BASIS` which mean we do not provide support for fork right now. Still, we have to think about it thanks to your message! Thank again for your interest and see you soon!

**Comment by lobamosa** [comment]
Hi, thanks for your reply. 
I have been able to mount the database thanks to your advice and the sql file you've provided.
Thanks, I understand for the onboarding, no problem.
