### ISSUE TITLE
fix: remove timeout

### ISSUE THREAD

**Issue by rap2hpoutre** [SocialGouv/mano#514]
Il y a des genre de timeouts qui sont trop bizarre et qui ne devraient pas être là, ex:

```
await new Promise((res) => setTimeout(res, 500));
```

Voir: https://github.com/SocialGouv/mano/pull/493#discussion_r831242466

**Comment by rap2hpoutre** [comment]
OK donc à priori en utilisant des setState dans des fonctions. Trop bien le lien :D

**Comment by arnaudambro** [comment]
rectification: dans le `Loader`, je les ai mis parce que je trouvais que c'était une meilleure UX, rien de bloquant à les retirer, juste une question de goût je pense.
c'est le genre de truc qui peut se faire discrètement pendant que l'autre est absent... 🥸
