### ISSUE TITLE
chore(security): remove all dangerouslySetInnerHTML

### ISSUE THREAD

**Issue by rap2hpoutre** [SocialGouv/mano#532]

**Comment by arnaudambro** [comment]
je serais plus mesuré si je peux me permettre: `dangerouslySetInnerHTML` n'est pas `dangerous` dès lors on est certain de ce qu'on met dedans -> https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

exemples: https://github.com/SocialGouv/mano/blob/8cd272de449af1f02770bda1a93cf040bdd2e2d1/dashboard/src/components/Card.js#L24
https://github.com/SocialGouv/mano/blob/8cd272de449af1f02770bda1a93cf040bdd2e2d1/dashboard/src/components/ButtonCustom.js#L34
