### ISSUE TITLE
sonarcloud !!

### ISSUE THREAD

**Issue by arnaudambro** [SocialGouv/mano#671]
@rap2hpoutre si tu sais pas quoi faire et que ça te motive...
j'en ai marre de fixer des tests partout et de quand même voir des ❌❌❌❌❌❌❌ à chaque fois !
j'ai du m'y pencher au moins 1/2h et j'ai tenté quelques trucs mais quand ça veut pas...

☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️☑️

**Comment by rap2hpoutre** [comment]
Tu parles de sonarcloud ou des tests end2end ? Si c'est les tests end to end franchement on dirait que ça va bien maintenant...

**Comment by arnaudambro** [comment]
fixed de682600e4a9985b3db50206730dfc3e5d5b5835
