### ISSUE TITLE
A11y tabs on mobile

### ISSUE THREAD

**Issue by rap2hpoutre** [SocialGouv/mano#744]
Maintenant qu'on a changé les couleurs, il faudrait probablement passer les textes en blanc sur cette partie (see: https://github.com/SocialGouv/mano/pull/733)

<img width="310" alt="Capture d’écran 2022-06-13 à 10 50 18" src="https://user-images.githubusercontent.com/1575946/173316395-c99c99bd-ba40-4584-bbdb-b90ebd1df3dc.png">

**Comment by arnaudambro** [comment]
#752
